version: 2.1

jobs:
  testMakefileDebian:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - run:
          name: "Download Makefile"
          command: 'curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/Makefile --output Makefile'
      - run:
          command: 'make aws-cdk'
      - run:
          command: 'make init-cdk-app project=TestProject'
      - run:
          command: 'cd TestProject && make build'

  testMakefileAmazonLinux:
    docker:
      - image: amazonlinux:latest
    steps:
      - run:
          name: "Download Makefile"
          command: 'curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/Makefile --output Makefile'


workflows:
  testMakefileWorkflow:
    jobs:
      - testMakefileDebian
      - testMakefileAmazon
