version: 2.1

orbs:
  shellcheck: circleci/shellcheck@2.2.4
  macos: circleci/macos@2.0.1

commands:
  validate:
    parameters:
      os:
        default: "unknown"
        type: string
    steps:
      - run:
          name: "Download Makefile"
          command: 'curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/Makefile --output Makefile'
      - run: 'make aws-cdk'
      - run: 'make init-cdk-app project=TestProject'
      - run: 'cd TestProject && make build'

jobs:
  testMakefileDebian:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - validate:
          os: 'Debian'

  testMakefileAmazonLinux:
      docker:
        - image: amazonlinux:latest
      steps:
        - run: 'yum -y install make sudo git'
        - run: 'curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -'
        - run: 'yum install -y nodejs'
        - validate:
            os: 'AmazonLinux'

  testMakefileMacOS:
       macos:
         xcode: 12.5.1
       steps:
        - validate:
            os: 'macOS'

workflows:
  testMakefileWorkflow:
    jobs:
      - shellcheck/check:
          dir: ./aws-cdk
      - testMakefileDebian
      - testMakefileAmazonLinux
      - testMakefileMacOS
