version: 2.1

# Orbs are reusable snippets of code that help automate repeated processes, speed up project setup,
# and make it easy to integrate with third-party tools.
orbs:
  shellcheck: circleci/shellcheck@2.2.4
  macos: circleci/macos@2.0.1
  github-super-linter: circleci/github-super-linter@1.0.0

# Describes reusable commands
commands:
  # Validate Makefile work building Test AWS CDK Java application.
  validate:
    parameters:
      os: # Unused parameter
        default: "unknown"
        type: string
    # Steps are a collection of executable commands which are run during a job
    steps:
      - run:
          name: "Download Makefile"
          command: 'curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/Makefile --output Makefile'
      - run: 'make aws-cdk'
      - run: 'make init-cdk-app project=TestProject'
      - run: 'cd TestProject && make build'

# Jobs are collections of steps.
jobs:
  # Describes job steps to execute Makefile validation with Debian Linux.
  debianLinux_CQ_AWSCDK:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - validate:
          os: 'Debian'

  # Describes job steps to execute Makefile validation with Amazon Linux.
  amazonLinux_CQ_AWSCDK:
      docker:
        - image: amazonlinux:latest
      steps:
        - run: 'yum -y install make sudo git'
        - run: 'curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -'
        - run: 'yum install -y nodejs'
        - validate:
            os: 'AmazonLinux'

  # Describes job steps to execute Makefile validation with macOS.
  testMakefileMacOs:
       macos:
         xcode: 12.5.1
       steps:
        - validate:
            os: 'macOS'

# A workflow is a set of rules for defining a collection of jobs and their run order.
workflows:
  validateAll:
    jobs:
      - github-super-linter/lint:
          scan-dir: ./
          version: v4

  validateAwsCdk:
    jobs:
      #- shellcheck/check:
      #    dir: ./aws-cdk
      - debianLinux_CQ_AWSCDK
      - amazonLinux_CQ_AWSCDK
      #- testMakefileMacOs

