version: 2.1

jobs:
  testMakefile:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - run:
          name: "Download Makefile"
          command: 'curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/Makefile --output Makefile'
      - run:
          name: "make aws-cdk installation"
          command: 'make aws-cdk'
      - run:
          command: 'make init-cdk-app project=TestProject'



workflows:
  testMakefileWorkflow:
    jobs:
      - testMakefile
