#!/bin/sh
set -e

# This script is meant for quick & easy install via:
#   $ curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/init-app-java | sudo sh

cdkInitApp()
{
    sh_c='sh -c'
    $sh_c "cdk init app --language=java"
}

cdkInitApp "$@" || exit 1