#!/bin/sh
set -e

# This script is meant for quick & easy install via:
#   $ curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/install | sudo sh
get_distribution() {
    lsb_dist=""
    if [ -r /etc/os-release ]; then
	lsb_dist="$(. /etc/os-release && echo "$ID")"
    fi
    echo "$lsb_dist"
}

do_install()
{
    os="$( uname -s | tr '[:upper:]' '[:lower:]' )"
    case $os in
	    linux)
	      lsb_dist="$( get_distribution | tr '[:upper:]' '[:lower:]' )"
	      if [ "$lsb_dist" = "ubuntu" ] || [ "$lsb_dist" = "debian" ]; then
		      npm install -g aws-cdk
		      sudo apt-get update
		      sudo apt install maven
		    fi
	      ;;
      darwin)
        echo $os
	      ;;
    esac
    sh_c='sh -c'
# $sh_c "npm install -g aws-cdk"
# $sh_c "yum install -y maven"
}

do_install
