#!/bin/sh
set -e

# This script is meant for quick & easy install via:
#   $ curl -fsSL https://raw.githubusercontent.com/raccoons-co/cloud-quarks/main/aws-cdk/sample-java | sh

do_install()
{
    sh_c='sh -c'
    $sh_c "mkdir ~/mkdir hello-cdk && cd hello-cdk && cdk init app --language java && mvn compile -q"
}

do_install
